// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeGame(arg1) {
  return window['go']['main']['App']['AnalyzeGame'](arg1);
}

export function BrowseCatalog(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowseCatalog'](arg1, arg2, arg3);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DeleteMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteMod'](arg1, arg2);
}

export function DownloadCatalogMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadCatalogMod'](arg1, arg2, arg3);
}

export function FetchModInfo(arg1) {
  return window['go']['main']['App']['FetchModInfo'](arg1);
}

export function GetMods(arg1) {
  return window['go']['main']['App']['GetMods'](arg1);
}

export function GetSingleModInfo(arg1) {
  return window['go']['main']['App']['GetSingleModInfo'](arg1);
}

export function InstallMod(arg1, arg2) {
  return window['go']['main']['App']['InstallMod'](arg1, arg2);
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}

export function LoadData(arg1) {
  return window['go']['main']['App']['LoadData'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function SaveData(arg1, arg2) {
  return window['go']['main']['App']['SaveData'](arg1, arg2);
}

export function ToggleMod(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ToggleMod'](arg1, arg2, arg3, arg4);
}
