// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {frontend} from '../models';

export function AnalyzeGame(arg1:string):Promise<main.GameAnalysis>;

export function BrowseCatalog(arg1:number,arg2:string,arg3:string):Promise<Record<string, any>>;

export function CloseWindow():Promise<void>;

export function DeleteMod(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DownloadCatalogMod(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function FetchModInfo(arg1:string):Promise<Record<string, any>>;

export function GetMods(arg1:string):Promise<Array<main.ModInfo>>;

export function GetSingleModInfo(arg1:string):Promise<Record<string, any>>;

export function InstallMod(arg1:string,arg2:string):Promise<Record<string, any>>;

export function LaunchGame(arg1:string):Promise<void>;

export function LoadData(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function OpenFile(arg1:Array<frontend.FileFilter>):Promise<string>;

export function OpenFolder():Promise<string>;

export function SaveData(arg1:string,arg2:string):Promise<void>;

export function ToggleMod(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<Record<string, any>>;
